version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: neverscapealone-discord:latest
    ports:
      - "6000:6000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/discord/logs:/code/logs:rw
